/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Jun-2018 6:34:58 PM 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "LV_CUSTOMER_VALUE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "LV_CUSTOMER_VALUE"
(
	"CCID" NUMBER(8) NOT NULL,
	"PROPERTY_ID" NUMBER(10) NOT NULL,
	"MLIFE_NUMBER" NUMBER(10) DEFAULT -1 NOT NULL,
	"DATE_CALC" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
	"DOMINANT_PLAY" VARCHAR2(50) NOT NULL,
	"SEGMENT" NUMBER(8) NOT NULL,
	"ROOM_ALLOWANCE" NUMBER(8,2) NOT NULL,
	"CARD_TIER" VARCHAR2(15) NOT NULL,
	"FREE_PLAY_AMOUNT" NUMBER(8,2) NOT NULL,
	"RESORT_CREDIT_AMOUNT" NUMBER(8,2) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "LV_CUSTOMER_VALUE" 
 ADD CONSTRAINT "PK_LV_CUSTOMER_VALUE"
	PRIMARY KEY ("PROPERTY_ID","DATE_CALC","CCID","MLIFE_NUMBER") 
 USING INDEX
;

CREATE INDEX "LV_CUSTOMER_VALUE_DATE_CALC_IDX"   
 ON  "LV_CUSTOMER_VALUE" ("DATE_CALC") 
;
