/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 12-Jun-2018 1:20:49 PM 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "REGIONAL_CUSTOMER_VALUES" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "REGIONAL_CUSTOMER_VALUES"
(
	"CCID" NUMBER(10) NOT NULL,
	"PROPERTY_ID" NUMBER(10) NOT NULL,
	"MLIFE_NUMBER" NUMBER(10) NULL,
	"DATE_CALC" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
	"DOMINANT_PLAY" VARCHAR2(50) NOT NULL,
	"POWER_RANK" NUMBER(3) NOT NULL,
	"POWER_VALUE" NUMBER(5) NOT NULL,
	"CARD_TIER" VARCHAR2(15) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "REGIONAL_CUSTOMER_VALUES" 
 ADD CONSTRAINT "PK_REGIONAL_CUSTOMER_VALUES"
	PRIMARY KEY ("PROPERTY_ID","DATE_CALC","CCID") 
 USING INDEX
;

CREATE INDEX "REGIONAL_CUSTOMER_VALUE_DATE_CALC_IDX"   
 ON  "REGIONAL_CUSTOMER_VALUES" ("DATE_CALC") 
;
